events {
    worker_connections 1024;
}

http {
    # --- 限流定义 ---
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    # 引入 conf.d 下的配置（包括你挂载的 default.conf）
    include /etc/nginx/conf.d/*.conf;
}